---
-

  hosts: all
  name: task_1
  ignore_errors: yes
  tasks: 
    - 
      file: 
        mode: "0755"
        path: /dvd
        state: directory
      name: "Repo mount_folder creation"
    - 
      mount: 
        fstype: iso9660
        opts: "ro,loop"
        path: /dvd/
        src: /dev/cdrom
        state: mounted
      name: mount_dvd
    - 
      name: yum_repo_BaseOS
      yum_repository: 
        baseurl: "file:///dvd/BaseOS"
        description: Local_baseos
        file: dvd1
        gpgcheck: false
        name: BaseOS
    - 
      name: yum_repo_AppStream
      yum_repository: 
        baseurl: "file:///dvd/AppStream"
        description: Local_appstream
        file: dvd2
        gpgcheck: false
        name: AppStream


- 
  hosts: managed_machine
  tasks: 
    - 
      name: Docker
      yum_repository: 
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        description: "docker YUM repo"
        gpgcheck: false
        name: docker
    - 
      package: 
        name: docker-ce-18.09.1-3.el7.x86_64
        state: present
    - 
      name: "Install Docker Module for Python"
      pip: 
        name: docker-py
    - 
      service: 
        name: docker
        state: started
    - 
      docker_image: 
        name: "httpd:latest"
        source: pull
      name: "Pull default Docker image"
    - 
      copy: 
        dest: /root/code/
        src: /root/code/code.html
      ignore_errors: true
    - 
      name: "website is ready"
      docker_container: 
        exposed_ports: 
          - 80/tcp
        image: httpd
        name: WebServer
        ports: 
          - "8888:80"
        state: started
        volumes: 
          - "/root/code:/usr/local/apache2/htdocs/"
      
